spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogging_application
    username: vaishalijogdande
    password: Vaishali@2024
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: vaishali
      password: 12345
      roles: ADMIN

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/

logging:
  level:
    org:
      framework:
        security:
          DEBUG


